### ISSUE TITLE
Show number of comments

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#29]
Let's show the number of comments in each post, under the post's title

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/f804bd68-121f-44ab-b94e-40fefb38927a.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/f804bd68-121f-44ab-b94e-40fefb38927a.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0c6b5890-f5b3-4f89-812a-8722f07935c6.log).

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/0c6b5890-f5b3-4f89-812a-8722f07935c6.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/e290d793-0ed2-475f-ac10-49230d974f48.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/e290d793-0ed2-475f-ac10-49230d974f48.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/df60e37d-d450-42f2-85e4-038a37c16181.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/df60e37d-d450-42f2-85e4-038a37c16181.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index pls

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/73ad1c55-dd40-4b3c-8532-b1cd56dc760a.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/5522a53b-2eb5-42c6-95af-e39f9492ac43.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/c2284297-779e-494b-8bcc-1972a79afab5.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/c2284297-779e-494b-8bcc-1972a79afab5.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/3e0ce9f8-bf4a-4aee-b1eb-d016978177b7.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@amihaiemil index site

**Comment by amihaiemil** [comment]
@charlesmike delete [this](https://www.amihaiemil.com/aboutme/about.html) page

**Comment by charlesmike** [comment]
> @charlesmike delete [this](https://www.amihaiemil.com/aboutme/about.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/0dfeddea-0a5d-4dc6-80a6-6ea0d251b27c.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike delete [this](https://www.amihaiemil.com/aboutme/about.html) page

**Comment by charlesmike** [comment]
> @charlesmike delete [this](https://www.amihaiemil.com/aboutme/about.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/ac455fa1-b4da-4f9c-a9f6-70562439a126.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://www.amihaiemil.com/sitemap.xml) sitemap

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://www.amihaiemil.com/sitemap.xml) sitemap

@amihaiemil the given page or sitemap does not seem to belong to the website hosted in this repo!

Make sure that the link starts with ``http://`` or ``https://`` followed by``ownerusername.github.io/...``. Do not use the CNAME or any other domain, even if it redirects toa page from this repo. Also, make sure that the link is specified in Markdown format. 

 If this condition is met and it still doesn't work please open an issue [here](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/7ac91c58-39d1-4b5e-b4f1-493d8d8bbc11.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/7ac91c58-39d1-4b5e-b4f1-493d8d8bbc11.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike hello there

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike hello index site delete index

**Comment by charlesmike** [comment]
> @charlesmike hello index site delete index

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike whatsup

**Comment by charlesmike** [comment]
> @charlesmike whatsup

@amihaiemil sorry, I do not understand what you mean. Check the [documentation](http://charles.amihaiemil.com/doc.html) for more details.
