### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#47]
The blog should have a "newsletter" page

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/1faf6b76-93e8-47c7-b6db-54ce0f10e8a2.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/1faf6b76-93e8-47c7-b6db-54ce0f10e8a2.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/9026a660-a059-431f-a173-05c32b74c72b.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/11f2f432-82b1-439a-b5cf-5c6af8d8abb7.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/9026a660-a059-431f-a173-05c32b74c72b.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/11f2f432-82b1-439a-b5cf-5c6af8d8abb7.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/6363fafe-5d09-4310-bf15-eb994400f6a7.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/6363fafe-5d09-4310-bf15-eb994400f6a7.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/6ecf737d-de89-4e5c-bc6b-41c008484082.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/6ecf737d-de89-4e5c-bc6b-41c008484082.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/8ed9e60a-3e45-4640-b89c-837d06b12dc0.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap with Chrome pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/8ed9e60a-3e45-4640-b89c-837d06b12dc0.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/6facaab1-57c5-47f2-8572-4098db11d55b.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/6facaab1-57c5-47f2-8572-4098db11d55b.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/b7ded29e-3392-46af-9593-76b2683e687b.log).

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/b7ded29e-3392-46af-9593-76b2683e687b.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index site pls

**Comment by charlesmike** [comment]
> @charlesmike index site pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a116da2d-c5cf-4e41-827c-50b5abe6ff5d.log).

**Comment by charlesmike** [comment]
> @charlesmike index site pls

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/a116da2d-c5cf-4e41-827c-50b5abe6ff5d.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete [this](https://www.amihaiemil.com/page4/) page

**Comment by charlesmike** [comment]
> @charlesmike delete [this](https://www.amihaiemil.com/page4/) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/bd348cf8-5484-407a-944d-cf64957207f2.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).
