### ISSUE TITLE
Invalid disqus uri host

### ISSUE THREAD

**Issue by g4s8** [amihaiemil/amihaiemil.github.io#48]
Disqus sometimes sends me emails when new comment was added in liked post, but this link to post is a link to `http://localhost:4000/`

**Comment by amihaiemil** [comment]
@g4s8 thanks, I'll have a look

**Comment by amihaiemil** [comment]
@g4s8 I reported it here: https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/bug_reports_feedback_localhost4000_links_in_prod/

Hopefully, someone answers. I have no other ideas :(

**Comment by amihaiemil** [comment]
@g4s8 I wrote some code to prevent Disqus from loading when on ``localhost``. I think the problem is caching on Disqus' side -- thread renders while I write the article and then the links to it are cached. 

I don't think it should happen anymore.
