### ISSUE TITLE
Implement tags

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#61]
In each blog post, tags should be clickable and lead the user to a page where all the posts with said tag are displayed.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike implement [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/820343db-019f-45e1-bd51-36c3fa964fbd.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/820343db-019f-45e1-bd51-36c3fa964fbd.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/f9b42dbe-0261-46d5-aa79-1c8fd50b62a8.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/f9b42dbe-0261-46d5-aa79-1c8fd50b62a8.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/98c430b2-c22a-4c93-98b0-754d7aba1d11.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/98c430b2-c22a-4c93-98b0-754d7aba1d11.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/478a268f-4f85-4edf-9ee9-c8803b5bd8cc.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/478a268f-4f85-4edf-9ee9-c8803b5bd8cc.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index please

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index please

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](https://charles.amihaiemil.com/logs.html?log=/d2129a2e-bed3-42d8-824b-1dec24a3be44.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/bd6f807a-3b76-44d3-a760-5ee1a0e2abaa.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/bd6f807a-3b76-44d3-a760-5ee1a0e2abaa.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/d97a0b0e-7960-4c68-bc12-e8dea481261c.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](https://charles.amihaiemil.com/logs.html?log=/d97a0b0e-7960-4c68-bc12-e8dea481261c.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/afbe1709-9b09-4019-9732-f74b3321e945.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please...

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/afbe1709-9b09-4019-9732-f74b3321e945.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index pls

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/5537a545-6d43-4c9a-b36d-9835db0c33d8.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please!

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please!

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/1ef8ad02-6d95-4b93-87be-24a01a80b315.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap please!

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/1ef8ad02-6d95-4b93-87be-24a01a80b315.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please!

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please!

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/98b28010-511f-4215-be9b-4bea58b57d50.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please!

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/98b28010-511f-4215-be9b-4bea58b57d50.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/088a5227-939d-4454-a23c-463140f2e22e.log).

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/088a5227-939d-4454-a23c-463140f2e22e.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/49c6f1ab-6883-4da6-b61f-c05d83795b07.log).

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/49c6f1ab-6883-4da6-b61f-c05d83795b07.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2018/09/05/who-is-a-fullstack-developer.html) new page

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/05/who-is-a-fullstack-developer.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a65cc614-b2c5-400a-8445-e3b08dc33c4a.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/05/who-is-a-fullstack-developer.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/a65cc614-b2c5-400a-8445-e3b08dc33c4a.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index pls

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/259ea4be-8670-47ae-99c7-68bdf4d1e3e0.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!
